### ISSUE TITLE
laravel5.3 配置完  php artisan vendor:publish  出现错误 

### ISSUE THREAD

**Issue by tosslife** [menthe/aliyun-ueditor#5]
[ErrorException]
  Declaration of Harris\UEditor\UEditorServiceProvider::boot() should be comp
  atible with Illuminate\Foundation\Support\Providers\RouteServiceProvider::b
  oot()

**Comment by tosslife** [comment]
需要在 UEditorServiceProvider.php 中 将 
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;
然后 class UEditorServiceProvider extends ServiceProvider

boot 方法中去掉参数 Route
再改成parent::boot ();

再执行php artisan vendor:publish 就可以了

**Comment by menthe** [comment]
谢谢提醒。前面没有测试过5.3，后面我测试一下，再发一个版本。
